# -*- coding: utf-8 -*-
"""data_cleanning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ka1j87ctdvwG71jskbV12JWfvZmgDOgd

# Goal

This data cleaning aims to solve the errors that might appear when using ann and txt to create conll file.
It does not change any word content, instead it just removes some unnecessary but disturbing punctuation.

# Function
"""
import sys
import re
import string

def text_cleanup (textfile):
    # This function clean up the text to remove some unnecessary but disturbing punctuation
    # input: txt file
    # output: create a txt file
    # basic rules:
    # " …" -> ","
    # " -" -> " "
    # " ," -> " "
    # "\\'" -> "\\"
    # " ." -> "."
    # ".," -> ","
    # ",." -> "."
    # "  " -> " "
    to_be_replaced = [" …"," -"," ,","\\'"," .",".,",",.","  "]
    replace = [","," "," ","\\",".",",","."," "]
    f = open(textfile, 'r')
    text = f.read()
    f.close()
    l = len(to_be_replaced)
    for i in range(l):
        text = text.replace(to_be_replaced[i],replace[i])
    for i in range(3):
        text = text.replace(to_be_replaced[l-1],replace[l-1])
    sentence = text.lstrip()
    text_list = [t.strip() for t in re.findall(r'\b.*?\S.*?(?:\b|$)', sentence)]
    text_final = " ".join(text_list)
    outputfile = open("{}_cleaned.txt".format(inFile[:-4]), "w")
    outputfile.write(text_final)
    outputfile.close()

if __name__ == "__main__":
    inFile = sys.argv[1]
    text_cleanup(inFile)
